name: ci

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        type: [alpine, debian]
        node: [18, 20, 22]
    env:
      AZURE_CONTAINER_REGISTRY_URL: hmctspublic.azurecr.io
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Hadolint Dockerfile
        # TODO https://github.com/hadolint/hadolint-action/pull/45
        uses: mblottiere/hadolint-action@3cfc69d4b25bafd525584886f73b385ee4f3ce28
        with:
          dockerfile: ./${{ matrix.type }}/Dockerfile
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Azure Container Repository
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Test - Node ${{ matrix.node }} ${{ matrix.type }}
        id: docker_build_test
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.type }}
          load: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY_URL }}/base/node:pr-${{ matrix.node }}-${{ matrix.type }}
          build-args: |
            NODE_VERSION=${{ matrix.node }}
      - name: Test - Node ${{ matrix.node }} ${{ matrix.type }}
        run: |
          chmod +x ./test-build.sh
          ./test-build.sh ${{ env.AZURE_CONTAINER_REGISTRY_URL }}/base/node pr-${{ matrix.node }}-${{ matrix.type }}
        shell: bash
      - name: Build and Push - Node ${{ matrix.node }} ${{ matrix.type }}
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.type }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.AZURE_CONTAINER_REGISTRY_URL }}/base/node:pr-${{ matrix.node }}-${{ matrix.type }}
          build-args: |
            NODE_VERSION=${{ matrix.node }}
